import type { Article, RateSnapshot } from "@/types/article";

export const FALLBACK_ARTICLES: Article[] = [
  {
    _id: "seed-1",
    title:
      "Jewar Airport Corridor Triggers 38% Price Surge Along Yamuna Expressway Stretch",
    body: "Property values along the 25km stretch connecting Jewar International Airport have surged as YEIDA releases fresh plots in the residential zone. Commercial operations began June 15 with the first IndiGo flight from Lucknow at 8:05 AM. Investors who registered in 2023 are now seeing returns that outpace most Delhi-NCR benchmarks by a significant margin, with demand showing no sign of cooling ahead of the airport's full capacity rollout. YEIDA Sectors 15C, 18 and 24A form the heart of the aerotropolis masterplan. Over six years, apartments along the corridor rose 158% (₹3,950 to ₹10,200/sq.ft) and plots surged 536% (₹1,650 to ₹10,500/sq.ft).",
    excerpt:
      "Property values along the 25km stretch connecting Jewar International Airport have surged as YEIDA releases fresh plots in the residential zone.",
    city: "Noida",
    type: "Govt",
    tags: ["Noida", "Govt", "Metro", "Investors"],
    isFeatured: true,
    isBreaking: true,
    author: "Property Desk · Greater Noida Correspondent",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    priceData: {
      area: "YEIDA Sector 18",
      ratePerSqft: 10200,
      changePercent: 3.4,
      changeDirection: "up",
    },
  },
  {
    _id: "seed-2",
    title: "Dwarka Expressway Sees Highest New Launches in Four Years",
    body: "DLF, M3M and Sobha collectively launched 4,200 units this quarter across five micro-markets, with average ticket size at ₹2.4 crore. Ready-to-move inventory commanding sharp premiums as buyers shift away from under-construction risk.",
    city: "Gurgaon",
    type: "Residential",
    tags: ["Gurgaon", "Residential", "Buyers"],
    isFeatured: false,
    isBreaking: false,
    author: "Realty Desk",
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-3",
    title: "Circle Rates in South Delhi Set for 15–18% Upward Revision",
    body: "Delhi government finalising revision — first in three years — affecting Vasant Vihar, Defence Colony and Greater Kailash zones. Stamp duty implications expected to shift buyer timelines ahead of the monsoon quarter.",
    city: "Delhi",
    type: "Rates",
    tags: ["Delhi", "Rates", "Govt", "Sellers"],
    isFeatured: false,
    isBreaking: false,
    author: "Policy Desk",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    priceData: {
      area: "Vasant Vihar",
      ratePerSqft: 22400,
      changePercent: 0.8,
      changeDirection: "down",
    },
  },
  {
    _id: "seed-4",
    title:
      "Aqua Line Extension to Sector 142 Clears Final DPR Hurdle — Eight New Stations Confirmed",
    body: "NMRC board approved the detailed project report for the Aqua Line extension from Sector 51 to Sector 142. Developers in affected sectors are already revising unsold inventory pricing upward, with some reporting 8–12% appreciation in under-construction units since the announcement. Construction is expected to commence Q4 2026 with a 36-month completion target.",
    city: "Noida",
    type: "Metro",
    tags: ["Noida", "Metro", "Govt", "Investors"],
    isFeatured: false,
    isBreaking: false,
    author: "Infrastructure Correspondent",
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-5",
    title:
      "Cyber City Office Rents Cross ₹180/sq.ft/month — Vacancy at 11-Year Low",
    body: "Grade A office vacancy in Gurgaon drops to 8.2%, the lowest since 2015. Global captive centres driving absorption as IT firms consolidate footprint in Sector 24 and 25A. Developers report zero vacancy in trophy buildings; secondary stock now commanding 22% premium over 2024 rents.",
    city: "Gurgaon",
    type: "Commercial",
    tags: ["Gurgaon", "Commercial", "Investors"],
    isFeatured: false,
    isBreaking: false,
    author: "Commercial Desk",
    publishedAt: new Date().toISOString(),
  },
  {
    _id: "seed-6",
    title: "DDA Housing Scheme 2026: 10,000 Flats in Narela Sector 14",
    body: "Applications open July 1. EWS and LIG categories prioritised in Phase 1. Online registration via dda.gov.in. Prices set between ₹28–45 lakh for 1BHK and 2BHK units across multiple tower blocks.",
    city: "Delhi",
    type: "Govt",
    tags: ["Delhi", "DDA", "Buyers", "Residential"],
    isFeatured: false,
    isBreaking: false,
    author: "Policy Desk",
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-7",
    title: "SBI Cuts Home Loan Rate to 8.4% for Women Borrowers Post RBI Cut",
    body: "Demand in the ₹80L–1.5Cr bracket expected to spike. Noida and Gurgaon periphery to benefit most, say analysts. Co-applicant incentives also enhanced for joint women borrowers.",
    city: "NCR",
    type: "Buyers",
    tags: ["Buyers", "Rates"],
    isFeatured: false,
    isBreaking: false,
    author: "Finance Desk",
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-8",
    title: "Resale Premiums in Sector 137 Noida Touch 22% Over Builder Price",
    body: "Ready-to-move inventory commanding sharp premiums as buyers avoid under-construction risk post-RERA. Sector 128, 137, and 150 lead resale activity across Greater Noida West.",
    city: "Noida",
    type: "Sellers",
    tags: ["Noida", "Sellers", "Residential"],
    isFeatured: false,
    isBreaking: false,
    author: "Markets Desk",
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-9",
    title: "UP RERA Orders Refund to 1,200 Buyers in Stalled Noida Project",
    body: "UP RERA directed a prominent Greater Noida developer to refund ₹312 crore with 10.85% interest following a 5-year delay. Landmark ruling expected to set precedent for delayed possession cases across UP.",
    city: "Noida",
    type: "Govt",
    tags: ["Noida", "RERA", "Buyers"],
    isFeatured: false,
    isBreaking: false,
    author: "Regulatory Desk",
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: "seed-10",
    title: "Sector 21 Greater Noida Plots Surge 31% on Film City Proximity",
    body: "Commercial plots adjacent to the upcoming Noida Film City project see speculative demand from hospitality and retail developers seeking early land positions near the entertainment hub.",
    city: "Noida",
    type: "Commercial",
    tags: ["Noida", "Film City", "Investors", "Commercial"],
    isFeatured: false,
    isBreaking: false,
    author: "Investment Desk",
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const FALLBACK_RATES: RateSnapshot[] = [
  {
    city: "Gurgaon",
    area: "DLF Phase 5",
    ratePerSqft: 18200,
    changePercent: 2.1,
    changeDirection: "up",
  },
  {
    city: "Noida",
    area: "Sector 150",
    ratePerSqft: 8600,
    changePercent: 3.4,
    changeDirection: "up",
  },
  {
    city: "Delhi",
    area: "Vasant Vihar",
    ratePerSqft: 22400,
    changePercent: 0.8,
    changeDirection: "down",
  },
];

export const TICKER_ITEMS = [
  { code: "GGN", area: "DLF Phase 5", rate: 18200, change: 2.1, dir: "up" as const },
  { code: "NOI", area: "Sector 150", rate: 8600, change: 3.4, dir: "up" as const },
  { code: "DEL", area: "Vasant Vihar", rate: 22400, change: 0.8, dir: "down" as const },
  { code: "GGN", area: "Dwarka Exp", rate: 11200, change: 1.7, dir: "up" as const },
  { code: "NOI", area: "Greater Noida West", rate: 6400, change: 4.1, dir: "up" as const },
  { code: "DEL", area: "Rohini Sec 24", rate: 12800, change: 1.2, dir: "up" as const },
  { code: "GGN", area: "Sohna Road", rate: 9400, change: 2.8, dir: "up" as const },
];

export const BREAKING_HEADLINES = [
  "RRTS Sahibabad–Delhi Corridor opens Q3 2026",
  "Circle rate hike imminent in South Delhi",
  "DDA Scheme 2026 applications open July 1",
  "Jewar Airport first commercial flight June 15",
  "Aqua Line extension DPR approved",
];
